-- Script para poblar las regiones y comunas de Chile
-- Insertar primero las regiones

INSERT INTO `code_room.region` (`id`, `code`, `name`, `romanNumber`, `createdAt`, `updatedAt`) VALUES
(1, 'XV', 'Región de Arica y Parinacota', 'XV', NOW(), NOW()),
(2, 'I', 'Región de Tarapacá', 'I', NOW(), NOW()),
(3, 'II', 'Región de Antofagasta', 'II', NOW(), NOW()),
(4, 'III', 'Región de Atacama', 'III', NOW(), NOW()),
(5, 'IV', 'Región de Coquimbo', 'IV', NOW(), NOW()),
(6, 'V', 'Región de Valparaíso', 'V', NOW(), NOW()),
(7, 'RM', 'Región Metropolitana de Santiago', 'XIII', NOW(), NOW()),
(8, 'VI', 'Región del Libertador General Bernardo O''Higgins', 'VI', NOW(), NOW()),
(9, 'VII', 'Región del Maule', 'VII', NOW(), NOW()),
(10, 'VIII', 'Región del Biobío', 'VIII', NOW(), NOW()),
(11, 'IX', 'Región de la Araucanía', 'IX', NOW(), NOW()),
(12, 'XIV', 'Región de Los Ríos', 'XIV', NOW(), NOW()),
(13, 'X', 'Región de Los Lagos', 'X', NOW(), NOW()),
(14, 'XI', 'Región Aysén del General Carlos Ibáñez del Campo', 'XI', NOW(), NOW()),
(15, 'XII', 'Región de Magallanes y de la Antártica Chilena', 'XII', NOW(), NOW());

-- Insertar las comunas de cada región

-- Región XV - Arica y Parinacota
INSERT INTO `code_room.comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Arica', 1, NOW(), NOW()),
('Camarones', 1, NOW(), NOW()),
('Putre', 1, NOW(), NOW()),
('General Lagos', 1, NOW(), NOW());

-- Región I - Tarapacá
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Iquique', 2, NOW(), NOW()),
('Alto Hospicio', 2, NOW(), NOW()),
('Pozo Almonte', 2, NOW(), NOW()),
('Camiña', 2, NOW(), NOW()),
('Colchane', 2, NOW(), NOW()),
('Huara', 2, NOW(), NOW()),
('Pica', 2, NOW(), NOW());

-- Región II - Antofagasta
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Antofagasta', 3, NOW(), NOW()),
('Mejillones', 3, NOW(), NOW()),
('Sierra Gorda', 3, NOW(), NOW()),
('Taltal', 3, NOW(), NOW()),
('Calama', 3, NOW(), NOW()),
('Ollagüe', 3, NOW(), NOW()),
('San Pedro de Atacama', 3, NOW(), NOW()),
('Tocopilla', 3, NOW(), NOW()),
('María Elena', 3, NOW(), NOW());

-- Región III - Atacama
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Copiapó', 4, NOW(), NOW()),
('Caldera', 4, NOW(), NOW()),
('Tierra Amarilla', 4, NOW(), NOW()),
('Chañaral', 4, NOW(), NOW()),
('Diego de Almagro', 4, NOW(), NOW()),
('Vallenar', 4, NOW(), NOW()),
('Alto del Carmen', 4, NOW(), NOW()),
('Freirina', 4, NOW(), NOW()),
('Huasco', 4, NOW(), NOW());

-- Región IV - Coquimbo
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('La Serena', 5, NOW(), NOW()),
('Coquimbo', 5, NOW(), NOW()),
('Andacollo', 5, NOW(), NOW()),
('La Higuera', 5, NOW(), NOW()),
('Paiguano', 5, NOW(), NOW()),
('Vicuña', 5, NOW(), NOW()),
('Illapel', 5, NOW(), NOW()),
('Canela', 5, NOW(), NOW()),
('Los Vilos', 5, NOW(), NOW()),
('Salamanca', 5, NOW(), NOW()),
('Ovalle', 5, NOW(), NOW()),
('Combarbalá', 5, NOW(), NOW()),
('Monte Patria', 5, NOW(), NOW()),
('Punitaqui', 5, NOW(), NOW()),
('Río Hurtado', 5, NOW(), NOW());

-- Región V - Valparaíso
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Valparaíso', 6, NOW(), NOW()),
('Casablanca', 6, NOW(), NOW()),
('Concón', 6, NOW(), NOW()),
('Juan Fernández', 6, NOW(), NOW()),
('Puchuncaví', 6, NOW(), NOW()),
('Quintero', 6, NOW(), NOW()),
('Viña del Mar', 6, NOW(), NOW()),
('Isla de Pascua', 6, NOW(), NOW()),
('Los Andes', 6, NOW(), NOW()),
('Calle Larga', 6, NOW(), NOW()),
('Rinconada', 6, NOW(), NOW()),
('San Esteban', 6, NOW(), NOW()),
('La Ligua', 6, NOW(), NOW()),
('Cabildo', 6, NOW(), NOW()),
('Papudo', 6, NOW(), NOW()),
('Petorca', 6, NOW(), NOW()),
('Zapallar', 6, NOW(), NOW()),
('Quillota', 6, NOW(), NOW()),
('Calera', 6, NOW(), NOW()),
('Hijuelas', 6, NOW(), NOW()),
('La Cruz', 6, NOW(), NOW()),
('Nogales', 6, NOW(), NOW()),
('San Antonio', 6, NOW(), NOW()),
('Algarrobo', 6, NOW(), NOW()),
('Cartagena', 6, NOW(), NOW()),
('El Quisco', 6, NOW(), NOW()),
('El Tabo', 6, NOW(), NOW()),
('Santo Domingo', 6, NOW(), NOW()),
('San Felipe', 6, NOW(), NOW()),
('Catemu', 6, NOW(), NOW()),
('Llaillay', 6, NOW(), NOW()),
('Panquehue', 6, NOW(), NOW()),
('Putaendo', 6, NOW(), NOW()),
('Santa María', 6, NOW(), NOW()),
('Limache', 6, NOW(), NOW()),
('Olmué', 6, NOW(), NOW()),
('Villa Alemana', 6, NOW(), NOW());

-- Región RM - Metropolitana de Santiago
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Santiago', 7, NOW(), NOW()),
('Cerrillos', 7, NOW(), NOW()),
('Cerro Navia', 7, NOW(), NOW()),
('Conchalí', 7, NOW(), NOW()),
('El Bosque', 7, NOW(), NOW()),
('Estación Central', 7, NOW(), NOW()),
('Huechuraba', 7, NOW(), NOW()),
('Independencia', 7, NOW(), NOW()),
('La Cisterna', 7, NOW(), NOW()),
('La Florida', 7, NOW(), NOW()),
('La Granja', 7, NOW(), NOW()),
('La Pintana', 7, NOW(), NOW()),
('La Reina', 7, NOW(), NOW()),
('Las Condes', 7, NOW(), NOW()),
('Lo Barnechea', 7, NOW(), NOW()),
('Lo Espejo', 7, NOW(), NOW()),
('Lo Prado', 7, NOW(), NOW()),
('Macul', 7, NOW(), NOW()),
('Maipú', 7, NOW(), NOW()),
('Ñuñoa', 7, NOW(), NOW()),
('Pedro Aguirre Cerda', 7, NOW(), NOW()),
('Peñalolén', 7, NOW(), NOW()),
('Providencia', 7, NOW(), NOW()),
('Pudahuel', 7, NOW(), NOW()),
('Quilicura', 7, NOW(), NOW()),
('Quinta Normal', 7, NOW(), NOW()),
('Recoleta', 7, NOW(), NOW()),
('Renca', 7, NOW(), NOW()),
('San Joaquín', 7, NOW(), NOW()),
('San Miguel', 7, NOW(), NOW()),
('San Ramón', 7, NOW(), NOW()),
('Vitacura', 7, NOW(), NOW()),
('Puente Alto', 7, NOW(), NOW()),
('Pirque', 7, NOW(), NOW()),
('San José de Maipo', 7, NOW(), NOW()),
('Colina', 7, NOW(), NOW()),
('Lampa', 7, NOW(), NOW()),
('Tiltil', 7, NOW(), NOW()),
('San Bernardo', 7, NOW(), NOW()),
('Buin', 7, NOW(), NOW()),
('Calera de Tango', 7, NOW(), NOW()),
('Paine', 7, NOW(), NOW()),
('Melipilla', 7, NOW(), NOW()),
('Alhué', 7, NOW(), NOW()),
('Curacaví', 7, NOW(), NOW()),
('María Pinto', 7, NOW(), NOW()),
('San Pedro', 7, NOW(), NOW()),
('Talagante', 7, NOW(), NOW()),
('El Monte', 7, NOW(), NOW()),
('Isla de Maipo', 7, NOW(), NOW()),
('Padre Hurtado', 7, NOW(), NOW()),
('Peñaflor', 7, NOW(), NOW());

-- Región VI - O'Higgins
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Rancagua', 8, NOW(), NOW()),
('Codegua', 8, NOW(), NOW()),
('Coinco', 8, NOW(), NOW()),
('Coltauco', 8, NOW(), NOW()),
('Doñihue', 8, NOW(), NOW()),
('Graneros', 8, NOW(), NOW()),
('Las Cabras', 8, NOW(), NOW()),
('Machalí', 8, NOW(), NOW()),
('Malloa', 8, NOW(), NOW()),
('Mostazal', 8, NOW(), NOW()),
('Olivar', 8, NOW(), NOW()),
('Peumo', 8, NOW(), NOW()),
('Pichidegua', 8, NOW(), NOW()),
('Quinta de Tilcoco', 8, NOW(), NOW()),
('Rengo', 8, NOW(), NOW()),
('Requínoa', 8, NOW(), NOW()),
('San Vicente', 8, NOW(), NOW()),
('Pichilemu', 8, NOW(), NOW()),
('La Estrella', 8, NOW(), NOW()),
('Litueche', 8, NOW(), NOW()),
('Marchihue', 8, NOW(), NOW()),
('Navidad', 8, NOW(), NOW()),
('Paredones', 8, NOW(), NOW()),
('San Fernando', 8, NOW(), NOW()),
('Chépica', 8, NOW(), NOW()),
('Chimbarongo', 8, NOW(), NOW()),
('Lolol', 8, NOW(), NOW()),
('Nancagua', 8, NOW(), NOW()),
('Palmilla', 8, NOW(), NOW()),
('Peralillo', 8, NOW(), NOW()),
('Placilla', 8, NOW(), NOW()),
('Pumanque', 8, NOW(), NOW()),
('Santa Cruz', 8, NOW(), NOW());

-- Región VII - Maule
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Talca', 9, NOW(), NOW()),
('Constitución', 9, NOW(), NOW()),
('Curepto', 9, NOW(), NOW()),
('Empedrado', 9, NOW(), NOW()),
('Maule', 9, NOW(), NOW()),
('Pelarco', 9, NOW(), NOW()),
('Pencahue', 9, NOW(), NOW()),
('Río Claro', 9, NOW(), NOW()),
('San Clemente', 9, NOW(), NOW()),
('San Rafael', 9, NOW(), NOW()),
('Cauquenes', 9, NOW(), NOW()),
('Chanco', 9, NOW(), NOW()),
('Pelluhue', 9, NOW(), NOW()),
('Curicó', 9, NOW(), NOW()),
('Hualañé', 9, NOW(), NOW()),
('Licantén', 9, NOW(), NOW()),
('Molina', 9, NOW(), NOW()),
('Rauco', 9, NOW(), NOW()),
('Romeral', 9, NOW(), NOW()),
('Sagrada Familia', 9, NOW(), NOW()),
('Teno', 9, NOW(), NOW()),
('Vichuquén', 9, NOW(), NOW()),
('Linares', 9, NOW(), NOW()),
('Colbún', 9, NOW(), NOW()),
('Longaví', 9, NOW(), NOW()),
('Parral', 9, NOW(), NOW()),
('Retiro', 9, NOW(), NOW()),
('San Javier', 9, NOW(), NOW()),
('Villa Alegre', 9, NOW(), NOW()),
('Yerbas Buenas', 9, NOW(), NOW());

-- Región VIII - Biobío
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Concepción', 10, NOW(), NOW()),
('Coronel', 10, NOW(), NOW()),
('Chiguayante', 10, NOW(), NOW()),
('Florida', 10, NOW(), NOW()),
('Hualqui', 10, NOW(), NOW()),
('Lota', 10, NOW(), NOW()),
('Penco', 10, NOW(), NOW()),
('San Pedro de la Paz', 10, NOW(), NOW()),
('Santa Juana', 10, NOW(), NOW()),
('Talcahuano', 10, NOW(), NOW()),
('Tomé', 10, NOW(), NOW()),
('Hualpén', 10, NOW(), NOW()),
('Lebu', 10, NOW(), NOW()),
('Arauco', 10, NOW(), NOW()),
('Cañete', 10, NOW(), NOW()),
('Contulmo', 10, NOW(), NOW()),
('Curanilahue', 10, NOW(), NOW()),
('Los Álamos', 10, NOW(), NOW()),
('Tirúa', 10, NOW(), NOW()),
('Los Ángeles', 10, NOW(), NOW()),
('Antuco', 10, NOW(), NOW()),
('Cabrero', 10, NOW(), NOW()),
('Laja', 10, NOW(), NOW()),
('Mulchén', 10, NOW(), NOW()),
('Nacimiento', 10, NOW(), NOW()),
('Negrete', 10, NOW(), NOW()),
('Quilaco', 10, NOW(), NOW()),
('Quilleco', 10, NOW(), NOW()),
('San Rosendo', 10, NOW(), NOW()),
('Santa Bárbara', 10, NOW(), NOW()),
('Tucapel', 10, NOW(), NOW()),
('Yumbel', 10, NOW(), NOW()),
('Alto Biobío', 10, NOW(), NOW()),
('Chillán', 10, NOW(), NOW()),
('Bulnes', 10, NOW(), NOW()),
('Cobquecura', 10, NOW(), NOW()),
('Coelemu', 10, NOW(), NOW()),
('Coihueco', 10, NOW(), NOW()),
('Chillán Viejo', 10, NOW(), NOW()),
('El Carmen', 10, NOW(), NOW()),
('Ninhue', 10, NOW(), NOW()),
('Ñiquén', 10, NOW(), NOW()),
('Pemuco', 10, NOW(), NOW()),
('Pinto', 10, NOW(), NOW()),
('Portezuelo', 10, NOW(), NOW()),
('Quillón', 10, NOW(), NOW()),
('Quirihue', 10, NOW(), NOW()),
('Ránquil', 10, NOW(), NOW()),
('San Carlos', 10, NOW(), NOW()),
('San Fabián', 10, NOW(), NOW()),
('San Ignacio', 10, NOW(), NOW()),
('San Nicolás', 10, NOW(), NOW()),
('Trehuaco', 10, NOW(), NOW()),
('Yungay', 10, NOW(), NOW());

-- Región IX - Araucanía
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Temuco', 11, NOW(), NOW()),
('Carahue', 11, NOW(), NOW()),
('Cunco', 11, NOW(), NOW()),
('Curarrehue', 11, NOW(), NOW()),
('Freire', 11, NOW(), NOW()),
('Galvarino', 11, NOW(), NOW()),
('Gorbea', 11, NOW(), NOW()),
('Lautaro', 11, NOW(), NOW()),
('Loncoche', 11, NOW(), NOW()),
('Melipeuco', 11, NOW(), NOW()),
('Nueva Imperial', 11, NOW(), NOW()),
('Padre Las Casas', 11, NOW(), NOW()),
('Perquenco', 11, NOW(), NOW()),
('Pitrufquén', 11, NOW(), NOW()),
('Pucón', 11, NOW(), NOW()),
('Saavedra', 11, NOW(), NOW()),
('Teodoro Schmidt', 11, NOW(), NOW()),
('Toltén', 11, NOW(), NOW()),
('Vilcún', 11, NOW(), NOW()),
('Villarrica', 11, NOW(), NOW()),
('Cholchol', 11, NOW(), NOW()),
('Angol', 11, NOW(), NOW()),
('Collipulli', 11, NOW(), NOW()),
('Curacautín', 11, NOW(), NOW()),
('Ercilla', 11, NOW(), NOW()),
('Lonquimay', 11, NOW(), NOW()),
('Los Sauces', 11, NOW(), NOW()),
('Lumaco', 11, NOW(), NOW()),
('Purén', 11, NOW(), NOW()),
('Renaico', 11, NOW(), NOW()),
('Traiguén', 11, NOW(), NOW()),
('Victoria', 11, NOW(), NOW());

-- Región XIV - Los Ríos
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Valdivia', 12, NOW(), NOW()),
('Corral', 12, NOW(), NOW()),
('Lanco', 12, NOW(), NOW()),
('Los Lagos', 12, NOW(), NOW()),
('Máfil', 12, NOW(), NOW()),
('Mariquina', 12, NOW(), NOW()),
('Paillaco', 12, NOW(), NOW()),
('Panguipulli', 12, NOW(), NOW()),
('La Unión', 12, NOW(), NOW()),
('Futrono', 12, NOW(), NOW()),
('Lago Ranco', 12, NOW(), NOW()),
('Río Bueno', 12, NOW(), NOW());

-- Región X - Los Lagos
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Puerto Montt', 13, NOW(), NOW()),
('Calbuco', 13, NOW(), NOW()),
('Cochamó', 13, NOW(), NOW()),
('Fresia', 13, NOW(), NOW()),
('Frutillar', 13, NOW(), NOW()),
('Los Muermos', 13, NOW(), NOW()),
('Llanquihue', 13, NOW(), NOW()),
('Maullín', 13, NOW(), NOW()),
('Puerto Varas', 13, NOW(), NOW()),
('Castro', 13, NOW(), NOW()),
('Ancud', 13, NOW(), NOW()),
('Chonchi', 13, NOW(), NOW()),
('Curaco de Vélez', 13, NOW(), NOW()),
('Dalcahue', 13, NOW(), NOW()),
('Puqueldón', 13, NOW(), NOW()),
('Queilén', 13, NOW(), NOW()),
('Quellón', 13, NOW(), NOW()),
('Quemchi', 13, NOW(), NOW()),
('Quinchao', 13, NOW(), NOW()),
('Osorno', 13, NOW(), NOW()),
('Puerto Octay', 13, NOW(), NOW()),
('Purranque', 13, NOW(), NOW()),
('Puyehue', 13, NOW(), NOW()),
('Río Negro', 13, NOW(), NOW()),
('San Juan de la Costa', 13, NOW(), NOW()),
('San Pablo', 13, NOW(), NOW()),
('Chaitén', 13, NOW(), NOW()),
('Futaleufú', 13, NOW(), NOW()),
('Hualaihué', 13, NOW(), NOW()),
('Palena', 13, NOW(), NOW());

-- Región XI - Aysén
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Coyhaique', 14, NOW(), NOW()),
('Lago Verde', 14, NOW(), NOW()),
('Aysén', 14, NOW(), NOW()),
('Cisnes', 14, NOW(), NOW()),
('Guaitecas', 14, NOW(), NOW()),
('Cochrane', 14, NOW(), NOW()),
('O''Higgins', 14, NOW(), NOW()),
('Tortel', 14, NOW(), NOW()),
('Chile Chico', 14, NOW(), NOW()),
('Río Ibáñez', 14, NOW(), NOW());

-- Región XII - Magallanes
INSERT INTO `comuna` (`name`, `regionId`, `createdAt`, `updatedAt`) VALUES
('Punta Arenas', 15, NOW(), NOW()),
('Laguna Blanca', 15, NOW(), NOW()),
('Río Verde', 15, NOW(), NOW()),
('San Gregorio', 15, NOW(), NOW()),
('Cabo de Hornos (Ex Navarino)', 15, NOW(), NOW()),
('Antártica', 15, NOW(), NOW()),
('Porvenir', 15, NOW(), NOW()),
('Primavera', 15, NOW(), NOW()),
('Timaukel', 15, NOW(), NOW()),
('Natales', 15, NOW(), NOW()),
('Torres del Paine', 15, NOW(), NOW());